// 代码生成时间: 2025-09-11 02:35:50
using System;
using System.Data;
using System.Data.SqlClient;
using System.Windows;

// This class represents the main window of the WPF application
public partial class MainWindow : Window
{
    private string connectionString;
    private string sqlCommand;

    public MainWindow()
    {
        InitializeComponent();
        connectionString = "Data Source=YourDataSource;Initial Catalog=YourDatabase;Integrated Security=True";
        sqlCommand = "SELECT * FROM Users WHERE Username = @Username AND Password = @Password";
    }

    // This method is called when the 'Login' button is clicked
    private void LoginButton_Click(object sender, RoutedEventArgs e)
    {
        try
        {
            // Get the username and password from the input fields
            string username = UsernameTextBox.Text;
            string password = PasswordTextBox.Password;

            // Use parameterized queries to prevent SQL injection
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                SqlCommand command = new SqlCommand(sqlCommand, connection);
                command.Parameters.AddWithValue("@Username", username);
                command.Parameters.AddWithValue("@Password", password);

                connection.Open();
                SqlDataReader reader = command.ExecuteReader();

                if (reader.Read())
                {
                    // If user is found, show a success message
                    MessageBox.Show("Login successful!");
                }
                else
                {
                    // If user is not found, show an error message
                    MessageBox.Show("Invalid username or password.");
                }
            }
        }
        catch (Exception ex)
        {
            // Handle any errors that occur during the login process
            MessageBox.Show($"An error occurred: {ex.Message}");
        }
    }

    // This method initializes the components of the window
    private void InitializeComponent()
    {
        // Your XAML code here, which will be automatically generated by Visual Studio when you create a new WPF Window
    }
}
